disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "mrtruongvu"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "logo.png"
  # secondaryLogo = "png.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Truong Vu"
  email = "truong.vu@live.de"
  image = "profile4.jpg"
  imageQuality = 96
#  headline = "Welcome to my world!"
  bio = "🇻🇳 🇩🇪"
  links = [
    { email = "mailto:truong.vu@live.de" },
#     { link = "https://link-to-some-website.com/" },
#     { discord = "https://discord.gg/invitecode" },
#     { facebook = "https://facebook.com/username" },
#     { flickr = "https://www.flickr.com/photos/username/" },
    { github = "https://github.com/mrtruongvu" },
#     { instagram = "https://instagram.com/username" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
    { linkedin = "https://linkedin.com/in/truongvu3" },
#     { medium = "https://medium.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { spotify = "https://open.spotify.com/user/userid" },
    { strava = "https://www.strava.com/athletes/40068121" },
#    { komoot = "https://link-to-some-website.com/" },

  ]
